from pydantic import BaseModel, ConfigDict, Field

class CourseBase(BaseModel):
    code: str = Field(
        ...,
        title='Course Code',
        pattern='^[A-Za-z]{3}[0-9]{4}$',
        example='FEL1234'
    )
    name: str = Field(
        ...,
        title='Course Name',
        min_length=10,
        max_length=50,
        example='Functional Programming Principles'
    )
    credit_hours: int = Field(
        ...,
        title='Credit Hours',
        description='Number of credit hours per week',
        gt=0,
        lt=10,
        example=4
    )

class CourseCreate(CourseBase):
    pass

class CourseGet(CourseBase):
    id: int = Field(
        ...,
        title='Unique primary key',
        description='Unique primary key auto-generated by database',
        gt=0,
        example=3
    )
    model_config = ConfigDict(from_attributes=True)

class CourseUpdate(BaseModel):
    code: str | None = Field(
        None,
        title='Course Code',
        pattern='^[A-Za-z]{3}[0-9]{4}$',
        example='FEL1234'
    )
    name: str | None = Field(
        None,
        title='Course Name',
        min_length=10,
        max_length=50,
        example='Functional Programming Principles'
    )
    credit_hours: int | None = Field(
        None,
        title='Credit Hours',
        description='Number of credit hours per week',
        gt=0,
        lt=10,
        example=4
    )
