from pydantic import BaseModel, ConfigDict, Field
from datetime import datetime

class EnrollmentBase(BaseModel):
    student_id: int = Field(
        ...,
        title='Unique primary key for each student',
        description='Unique primary key for each student auto-generated by database',
        gt=0,
        example=3
    )
    course_id: int = Field(
        ...,
        title='Unique primary key for each course',
        description='Unique primary key for each course auto-generated by database',
        gt=0,
        example=3
    )

# Don't allow users to set or change date
class EnrollmentCreate(EnrollmentBase):
    pass

class EnrollmentGet(EnrollmentBase):
    date: datetime = Field(
        ...,
        title='Enrollment Date',
        description='The date when the student enroll in the course'
    )

    model_config = ConfigDict(from_attributes=True)
